# Site settings
title: /dev/caffeine
name: /dev/caffeine
subtitle: A programmer is a biological machine for turning coffee into code
author: Chris Flipse
email: cflipse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The infrequently updated blog of a software developer working in the DC region.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://blog.devcaffeine.com # the base hostname & protocol for your site
twitter_username: cflipse
github_username:  cflipse

exclude: [.bundle, bin, vendor]


titlecase: true

permalink: /:year/:month/:title/

# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - footnotes
highlighter: pygments

gems:
  - jekyll-paginate
  - octopress-ink
  - octopress-feeds
  - octopress-paginate
  - octopress-social
  - octopress-gist
  - octopress-codefence
  - octopress-solarized

disqus_short_name: devcaffeine

excerpt_link: "Read on &rarr;"
excerpt_separator: <!-- more -->

paginate: 5
