# Site settings
title: /dev/caffeine
subtitle: A programmer is a biological machine for turning coffee into code
email: cflipse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The infrequently updated blog of a software developer working in the DC region.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://blog.devcaffeine.com # the base hostname & protocol for your site
twitter_username: cflipse
github_username:  cflipse

exclude: [.bundle, bin, vendor]


titlecase: true

permalink: /:year/:month/:title/


# Build settings
markdown: redcarpet
redcarpet:
  extensions:
    - fenced_code_blocks
rdiscount:
  extensions:
    - autolink
    - footnotes
    - smart
highlighter: pygments

gems:
  - octopress-solarized
  - octopress-ink


disqus_short_name: devcaffeine
