# Site settings
title: /dev/caffeine
subtitle: A programmer is a biological machine for turning coffee into code
email: cflipse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://devcaffeine.com" # the base hostname & protocol for your site
twitter_username: cflipse
github_username:  cflipse

# Build settings
markdown: kramdown
