# Site settings
title: /dev/caffeine
name: /dev/caffeine
subtitle: A programmer is a biological machine for turning coffee into code
author: Chris Flipse
email: cflipse@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The infrequently updated blog of a software developer working in the DC region.
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://blog.devcaffeine.com # the base hostname & protocol for your site
twitter_username: cflipse
github_username:  cflipse

exclude: [.bundle, bin, vendor]

titlecase: true

permalink: /:year/:month/:title/

# Build settings

plugins:
  - jekyll-paginate
  - octopress-social
  - jekyll-feed
  - jekyll-autoprefixer
  - jekyll-livereload   # for dev
  - 'jekyll/graphviz'


livereload: true
reload_port: 56789



disqus:
  shortname:  devcaffeine
  comments_link_text: Comments
  comments_disabled_link_text: Comments disabled

excerpt_link: "Read on &rarr;"
excerpt_separator: <!-- more -->

graphviz:
  options: '-Tsvg -Npenwidth=2.5 -Nshape=box -Nstyle=rounded -Ependwidth1 -Ncolor="#3d1f00" -Nmargin="0.35,0.15" -Earrowsize=0.7'
  command: 'dot'


paginate: 5
